# Generated by Django 3.1.6 on 2021-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='Users/Profile_Picture'),
        ),
    ]
