# Generated by Django 2.2.12 on 2021-02-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customerdetails_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='profile_picture',
        ),
    ]
