# Generated by Django 2.2.12 on 2021-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customerdetails_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='Users/Profile_Picture'),
        ),
    ]
