# Generated by Django 3.1.6 on 2021-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customerdetails_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='reffered_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
