from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_homepage, name='user_homepage'),
    path('login/',views.user_signin,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('signup/', views.user_signup,name='signup'),
    path('mobile/',views.mobile_login,name='mobile_login'),
    path('otp_verify/', views.otp_verify,name='Otp_verify'),
    path('dashboard/', views.dashboard_overview,name='user_dashboard'),
    path('user_profile/<int:id>/', views.user_profile,name='user_profile'),
    path('wishlist/', views.dashboard_my_wishlist,name='wishlist'),
    path('wallet/', views.dashboard_my_wallet,name='wallet'),
    path('rewards/', views.dashboard_my_rewards,name='rewards'),
    path('myorders/', views.dashboard_my_orders,name='my_orders'),
    path('myoffers/', views.latest_offers,name='latest_offers'),
    path('myitems/<int:id>/',views.dashboard_my_order_items,name='my_items'),
    path('my_address/', views.dashboard_my_address,name='my_address'),
    path('add_address/', views.dashboard_add_address,name='dashboard_add_address'),
    path('edit_address/<int:id>/',views.dashboard_update_address,name='dashboard_update_address'),
    path('delete_address/<int:id>/', views.dashboard_my_address_delete,name='delete_address'),
    path('shop_grid/', views.shop_grid,name='shopgrid'),
    path('product_view/<int:id>/',views.single_product_view,name='product_view'),
    path('cart/', views.view_cart,name='view_cart'),
    path('checkout/', views.checkout,name='checkout'),
    path('update_item/', views.update_item,name='update_item'),
    path('process_order/',views.process_order,name='process_order'),
    path('order_placed/<int:id>/', views.order_placed,name='order_placed'),
    path('bills/<int:id>/',views.order_bill,name='order_bill'),
    path('category/<int:id>/', views.category,name='category'),
    path('coupen_process/',views.coupen_process,name='coupen_process'),
    path('myorder_cancell/<int:id>/',views.dashboard_myorder_cancell,name='dashboard_myorder_cancell'),
    path('my_cancelled_order/',views.dashboard_my_cancelled_items,name='dashboard_my_cancelled_items'),
    path('reffral_signup/<str:refferal_code>/',views.refferal_signup,name='refferal_signup'),
]